- ping.c
Interpreting floating-point numbers from the command line based on the
current locale is a bad idea.
Original bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1283277
> ping: always use POSIX locale when parsing -i

- doc/Makefile
- doc/docbook2man-spec.pl
This change makes iputils builds reproducible.
> doc: don't timestamp manpages by default

- Makefile
ping fails to compile with uClibc based toolchains with the error
undefined reference to `__finite'
This commit links ping against libm to resolve the math library function
finite().
Note, this error is not seem with glibc based toolchains because finite seems to be resolved in both libm and libc.
> ping: link against libm

- traceroute6.c
The linux (at least) manpage says:
After the trip time, some additional annotation can be printed: !H, !N, or !P (host, network or protocol unreachable), !S (source route failed), !F (fragmentation needed), !X (communication administratively prohibited), !V (host precedence violation), !C (precedence cutoff in effect), or !<num> (ICMP unreachable code <num>). If almost all the probes result in some kind of unreachable, traceroute will give up and exit.
your code says: "ICMP6_DST_UNREACH_ADMIN" -> !S
you really mean !X
> 'admin prohibited' should print !X not !S.

- ping.c
- ping_common.c
The first one is a revert of an old commit attempting to fix https://bugzilla.redhat.com/show_bug.cgi?id=1061867 but introducing other issues that is obsoleted meanwhile by a better fix from Jason A. Donenfeld <Jason@zx2c4.com>.
The second one fixes a bug in -I option parsing where device gets assigned the IP address even though it should only get assigned device names.
A bit more detailed information can be found in the respective commit messages.
> fix two issues observed when using -I option with IP addresses

- ping.c
The code later fails anyways (as the original comment suggests), which
results in a weird recvmsg() loop that times out eventually.
Reproducer:
./ping -c 1 -s 65530 127.0.0.1
> ping: do not allow oversized packets to root

- ping6_common.c
When the sin6_family was set to 0, the initial probe connect()
could have succeeded instead of failing.
Fixes #57.
> correctly initialize first hop

- arping.c
- doc/arping.sgml
Also, give a less misleading error when a device cannot be automatically
determined and has to be specified by the user using the -I option.
> arping,doc: fix documentation of -I

- ping.c
- ping.h
ping "passes" the device variable to ping6_common.c, but it's not visible
there.
Original patch by Xin Long <lucien.xin@gmail.com>.
> fix ping -6 -I

- ping.c
According to `man connect(2)`, EACCES can be set either when pinging a
broadcast address, or when a local firewall rule is in place.
Easily reproduced by running `ip route add prohibit <ipaddr>` and then
trying to ping the address.
> ping: fix error message when getting EACCES from connect()

- ping.c
- ping6_common.c
Or the default route is used. Not binding the probe_fd to the same device will result wrong source address being selected (I get a warning for this).
I've only tested for IPv4 because I don't have access to IPv6.
This closes #55.
> ping: also bind the ICMP socket to the specific device

- ping.c
- ping.h
- ping6_common.c
- ping_common.c
A mismatch in timeval format (for eg. between the traceroute icmp packet and ping icmp packet when id & seq are the same) could cause ping to read an arbitrarily large timeval and thus cause ping to wait for response for an arbitrarily large value of time.
In this change, if a pattern was supplied in outgoing echo request, then it is validated on the incoming echo response so that ping's icmp packets are not confused with other applications' icmp packets
> Add strict pattern matching on response when pattern was provided

- ping_common.c
Original bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1410114
> ping: prevent possible double free after cap_free()

- arping.c
Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1387542
> arping: exit if network disappears while running

- ping.c
Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1373333.
> fix multicast setsockopt calls on big endian

- traceroute6.c
The memory pointed to by hostname is freed by freeaddrinfo so we must
copy the hostname to use it later. You can observe this when invoking
traceroute6 like 'traceroute6 www.google.com' and seeing the garbage
printed after "traceroute to ", or using ASAN.
> traceroute6: Fix use-after-free for hostname

- traceroute6.c
When we call idna_to_ascii_lz, it allocates memory for the output, which
is put into the idn variable. According to the man page, we're required
to free it. This change simply frees the memory if it was allocated.
Here's the valgrind output from the leak:
==30708== 16 bytes in 1 blocks are definitely lost in loss record 1 of 2
==30708==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==30708==    by 0x50453BF: idna_to_ascii_4z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15)
==30708==    by 0x5045577: idna_to_ascii_8z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15)
==30708==    by 0x50455D9: idna_to_ascii_lz (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15)
==30708==    by 0x401FAB: main (traceroute6.c:454)
> traceroute6: Fix leaking the idn memory

- traceroute6.c
Tracing to an IPv6 address was broken in 40fd68a784 when fixing tracing
to a hostname. It correctly moved the assignment to after the memcpy
into 'to', but that code path is only executed when tracing to a
hostname. The fix just moves the assignment to after the code paths for
filling out 'to' for both IPv6 addresses and hostnames.
Here's output from the current master branch:
>nate@ubuntu-testing:~/src/iputils⟫ sudo ./traceroute6 2607:f8b0:4006:80d::2004
traceroute to 2607:f8b0:4006:80d::2004 (2607:f8b0:4006:80d::2004) from 2604:a880:0:1010::1855:a001, 30 hops max, 24 byte packets
sendto: Invalid argument
1 traceroute: wrote 2607:f8b0:4006:80d::2004 24 chars, ret=-1
*sendto: Invalid argument
traceroute: wrote 2607:f8b0:4006:80d::2004 24 chars, ret=-1
^C
And with this patch: …
> traceroute6: Fix traceroute to IPv6 address

- ping_common.c
See 'man poll' or fs/select.c in kernel sources, POLLERR is ignored in
events and if error happens it will be returned regardless.
Signed-off-by: Cyril Hrubis <metan@ucw.cz>
> ping_common.c: POLLERRR is ignored in events

- Makefile
- arping.c
Kernel documentation gives pretty clear recommendation: do not use libsysfs.
This commit removes use of that library, and replaces functionality with
opening files oneself.
Reference: https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/sysfs-rules.rst
Signed-off-by: Sami Kerola <kerolasa@iki.fi>
> arping: do not use libsysfs to read from /sys

- ping.c
The message has no value for the user, even if verbose mode has been requested.
Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1501110.
> ping: remove spurious error message

- tracepath.c
This fixes the following issue.
==2522==ERROR: AddressSanitizer: heap-buffer-overflow on address
0x6060000009c0 at pc 0x55a6b4d1b2de bp 0x7ffd16c1d670 sp 0x7ffd16c1ce20
READ of size 128 at 0x6060000009c0 thread T0
#0 0x55a6b4d1b2dd in __asan_memcpy (/home/src/iputils/tracepath+0xc52dd)
#1 0x55a6b4d6cce3 in main /home/src/iputils/tracepath.c:473:3
#2 0x7f039dccff69 in __libc_start_main (/usr/lib/libc.so.6+0x20f69)
#3 0x55a6b4c717e9 in _start (/home/src/iputils/tracepath+0x1b7e9)
0x6060000009c0 is located 0 bytes to the right of 64-byte region [0x606000000980,0x6060000009c0)
allocated by thread T0 here:
#0 0x55a6b4d31561 in malloc (/home/src/iputils/tracepath+0xdb561)
#1 0x7f039dd8eb11 in gaih_inet.constprop.7 (/usr/lib/libc.so.6+0xdfb11)
#2 0x7f039dd90373 in __GI_getaddrinfo …
> tracepath: fix heap-buffer-overflow [asan]

- tracepath.c
While updating Gentoo's ebuild I noticed that it was just luck that *tracepath6* symlink caused IPv6 resolution because IPv6 is the default on most systems. But if you switch the defaults a symlinked *tracepath6* -> *tracepath* will not do what you expect.
Looks like it is only Gentoo installing *tracepath6* symlink. Not sure if we should get rid of the *tracepath6* symlink at all. However, this addition shouldn't hurt.
> tracepath: Support calling `tracepath` as `tracepath4` or `tracepath6`

- ping.c
- ping.h
- ping6_common.c
IP_RECVERR for raw socket was broken until 2.4.9.
Removed code was added as extern int working_recverr in
iputils-ss010805 (searching in old tarballs).
See also somehow related bug in various distros:
https://bugs.debian.org/709052
https://bugzilla.redhat.com/73660
https://bugzilla.opensuse.org/927831
> ping: Remove workaround for bug in IP_RECVERR on raw sockets

- ping6_common.c
This reverts commit e25568f5e580d5631f533ae8474bcca40a011690.
as it breaks ping to local IPv6 interfaces:
$ ip addr |grep 'inet6'
inet6 fe80::fc54:ff:fe2d:cc21/64 scope link
$ ./ping -6 fe80::fc54:ff:fe2d:cc21
connect: Invalid argument
Fixes #99 (regression in #57).
> ping: Allow to ping IPv6 link-local scope address without link specification

- doc/ping.xml
ifconfig and netstat are still widely used, but it's a time
to propagate their replacements ip and ss.
Signed-off-by: Petr Vorel <pvorel@suse.cz>
> doc/ping: Replace deprecated commands in "SEE ALSO" section

- doc/ping.xml
db77fb5 (Revert "correctly initialize first hop") allows to ping IPv6
link-local scope address without link specification.
It used to be possible in the past: added in f68eec0 ("ping: perform
dual-stack ping by default") and removed again in e25568f ("correctly
initialize first hop").
Signed-off-by: Petr Vorel <pvorel@suse.cz>
> doc/ping: Update Interface section

- ping_common.c
Upon POLLERR, ping reads from the socket and, unless there is
an errno other than EAGAIN or EINTR, it will not read the error
queue.
However, due to races on sk->sk_err, it is more robust to
always read the error queue when the socket read retruns
an EAGAIN and poll returns POLLERR.
Fixes #74
> ping: read from error queue when POLLERR is set

- ping6_common.c
The use of the && operator instead of || within ping6_run() results
in only the first setsockopt() call for IPV6_PKTINFO/SO_BINDTODEVICE
getting executed if it returns success, rather than all setsockopt()
calls as intended.
Fixes #88
Signed-off-by: Duncan Eastoe <deastoe@vyatta.att-mail.com>
> ping6: Fix device binding

- ping_common.c
Previously, ping rounded individual times down to the next lower 10us.
Doing any statistics on these values lead to wrong results. The summary
display is correct, but due to this bug a different value than using the
min/max/avg of the individual results. This commit fixes the rounding.
> Ping: Correct rounding of timing displays

- ping.c
- ping.h
Don't use AI_CANONIDN flag for getaddrinfo() on C locale as it tries to
convert ACE encoded names (i.e. containing the xn-- prefix) into current
locale which fails for C:
$ LC_ALL=C ping -c1 www.xn--kleine-knig-yfb.de
ping: www.xn--kleine-knig-yfb.de: Parameter string not correctly encoded
With this fix is working:
$ LC_ALL=C ping -c1 www.xn--kleine-knig-yfb.de
PING antares.xn--kleine-knig-yfb.de (94.130.110.236) 56(84) bytes of data.
64 bytes from antares.kleine-koenig.org (94.130.110.236): icmp_seq=1 ttl=50 time=18.7 ms
NOTE: Obviously pinging non ACE encoded name with C locale still fail:
$ LC_ALL=C ping -c1 www.kleine-könig.de
ping: www.kleine-könig.de: Parameter string not correctly encoded
Fixes: #130
Signed-off-by: Petr Vorel <pvorel@suse.cz>
> ping: Fix ping name encoded using ACE on C locale

- ping.c
clang complains:
ping.c:813:57: warning: implicit conversion from 'int' to 'char' changes value from 137 to -119 [-Wconstant-conversion]
rspace[1+IPOPT_OPTVAL] = (options & F_SO_DONTROUTE) ? IPOPT_SSRR
~                              ^~~~~~~~~~
../../../../../../usr/include/netinet/ip.h:263:21: note: expanded from macro 'IPOPT_SSRR'
#define IPOPT_SSRR              137             /* strict source route */
^~~
ping.c:814:6: warning: implicit conversion from 'int' to 'char' changes value from 131 to -125 [-Wconstant-conversion]
: IPOPT_LSRR;
^~~~~~~~~~
../../../../../../usr/include/netinet/ip.h:260:21: note: expanded from macro 'IPOPT_LSRR'
#define IPOPT_LSRR              131             /* loose source route */
^~~
Signed-off-by: Brian Norris <computersforpeace@gmail.com>
> ping: Fix signed overflow/conversion warning

- tracepath.c
strace ./tracepath -6 fe80::8895:e2af:e96e:fd8f
Previously was address too short:
sendto(3, "\1\0\0\0\0\0\0\0\307\36N[\0\0\0\0w_\f\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 127952, 0, {sa_family=AF_INET6, sin6_port=htons(44444), inet_pton(AF_INET6, "fe80::", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EMSGSIZE (Message too long)
After fix is correct:
sendto(3, "\1\0\0\0\0\0\0\0\300\36N[\0\0\0\0'B\3\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 127952, 0, {sa_family=AF_INET6, sin6_port=htons(44444), inet_pton(AF_INET6, "fe80::8895:e2af:e96e:fd8f", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EMSGSIZE (Message too long)
Fixes: e669c86 tracepath: fix heap-buffer-overflow [asan]
> tracepath: Fix copying input address

- arping.c
- ping.h
- tracepath.c
- traceroute6.c
Add missing AI_IDN and NI_IDN declarations.
Bug: https://bugs.gentoo.org/503914
> Fix build on MUSL

- ping.c
- ping.h
Commit 99f67db used AI_CANONIDN in a way, which broke compilation on
systems where AI_CANONIDN is not defined in netdb.h (e.g. glibc < 2.3.4,
alternative libcs that don't support IDN: e.g. current musl 1.1.19 and
uClibc-ng 1.0.30) when not using the system libidn2.
Fixes: 99f67db ping: Fix ping name encoded using ACE on C locale
Reported-by: Nicholas Fish
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>
> ping: Fix AI_CANONIDN usage on some systems

- ping.c
- ping6_common.c
- ping_common.c
"timeval" struct is 8 bytes in x86 but it is 16 bytes in x86_64.
So I think these comments are a little bit confusing.
> The first 8 bytes	and the sequence number is an ascending integer.  The first several bytes of the data portion are used to hold a UNIX "timeval" struct in VAX of the data portion are used to hold a UNIX "timeval" struct in VAX byte-order, to compute the round-trip time.
> Fixed comment of pinger functions

- ping_common.c
Rounding of triptimes like 17950 usec were printed as 17.10 ms instead of the correct 18.0 ms.
Was: (17950 % 1000 -> 950 + 50 -> 1000 / 100 -> 10)
Should be: (17950 + 50 -> 18000 % 1000 -> 0 / 100 -> 0)
> Fix Rounding Issue #141

- doc/ninfod.xml
It's a very trivial fix for a typo in the man page of `ninfod`. I noticed this recently and suppose it helps nevertheless :)
> doc/ninfod: Fix the debug mode option (-a -> -d)

- ping.c
Commit d141cb6 ("ping: work with older kernels that don't support ping
sockets") fixed #54 with handling EPROTONOSUPPORT for IPv6. But some
systems return EPROTONOSUPPORT also for IPv4 (Debian 9.5 based container
with kernel 4.10).
NOTE: inet_create() (IPv4) and inet6_create() (IPv6) implementations in
kernel also returns ESOCKTNOSUPPORT (Socket type not supported), but we
check that with assert:
assert(socktype == SOCK_DGRAM || socktype == SOCK_RAW);
Fixes: #129
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>
> ping: Fallback raw protocol for EPROTONOSUPPORT also on IPv4

- meson.build
In systems without the headers for idn2, the build is failing as we
always set USE_IDN to 1.
Signed-off-by: Victor Toso <victortoso@redhat.com>
> build-sys: Check if optional idn2 was found

- arping.c
Useful for using arping without having a local IP-address.
Reviewed-by: Sami Kerola <kerolasa@iki.fi>
Reference: https://github.com/iputils/iputils/pull/84
> arping: honor setting source to 0.0.0.0

- ping.c
- ping6_common.c
The getifaddrs(3) can return invalid data when system call is interrupted.
Issue was fixed in glibc 2.28 (relesed 2018-08-01). It is fair to assume
there are systems with older libc so make the ping more robust and check
ifa->ifa_name is not NULL before using it.
Reference: https://sourceware.org/bugzilla/show_bug.cgi?id=21812
Addresses: https://github.com/iputils/iputils/issues/112
Signed-off-by: Sami Kerola <kerolasa@iki.fi>
> ping: check getifaddrs(3) ifa_name data before use

- meson.build
- ninfod/meson.build
...instead of hard-coding 'sbin'.
> Use the value of sbindir to install rinfod, rarpd & ninfod

- .travis.yml
- doc/meson.build
- meson.build
The first commit improves the error messages when building with older versions of Meson (+ updates the project version), the second commit makes `setcap` really optional, and the third commit removes the old dependency on `docbook-xsl`.
So none of these changes are critical fixes, but they should improve the build experience in certain cases.
> Various fixes and improvements for the build system

- ninfod/ninfod_name.c
Build of ninfod with nettle fails on:
/home/test/autobuild/run/instance-1/output/host/bin/mips64el-linux-gcc  -o ninfod/ninfod 'ninfod/0cb6efe@@ninfod@exe/ni_ifaddrs.c.o' 'ninfod/0cb6efe@@ninfod@exe/ninfod.c.o' 'ninfod/0cb6efe@@ninfod@exe/ninfod_addrs.c.o' 'ninfod/0cb6efe@@ninfod@exe/ninfod_core.c.o' 'ninfod/0cb6efe@@ninfod@exe/ninfod_name.c.o' -Wl,--no-undefined -Wl,--as-needed -Wl,-O1 -Wl,--start-group libcommon.a -lcap /home/test/autobuild/run/instance-1/output/host/usr/bin/../mips64el-buildroot-linux-uclibc/sysroot/usr/lib/libnettle.so -Wl,--end-group -pthread '-Wl,-rpath,$ORIGIN/..:/home/test/autobuild/run/instance-1/output/host/usr/bin/../mips64el-buildroot-linux-uclibc/sysroot/usr/lib' -Wl,-rpath-link,/home/test/autobuild/run/instance-1/output/build/iputils-s20190515/build/:/home/te …
> ninfod/ninfod_name.c: fix build with nettle

- meson.build
commit 418d8be ("build-sys: fix build with NLS") fixed problems for
default packages using libintl. Fix also traceroute6 (build it must be
enabled with -DBUILD_TRACEROUTE6=true).
Signed-off-by: Petr Vorel <pvorel@suse.cz>
> traceroute6: fix build with NLS

- build-aux/setcap-setuid.sh
The previous change only updated the comment, not the actual code.
This commit updates the code in-line with the comment (removes the effective bit).
> Update shell command in line with comment.

- Makefile
None of the Makefile targets create a file called like the target.
Therefore all targets are declared to be phony.
> Makefile: Make all targets phony

- arping.c
- tracepath.c
- traceroute6.c
The gettimeofday() is obsolete.  Secondly, ensure time jumps do not effect
measurements by using monotonic time.
Signed-off-by: Sami Kerola <kerolasa@iki.fi>
> tracepath: use clock_gettime() rather gettimeofday()

- clockdiff.c
- iputils_common.c
- iputils_common.h
- meson.build
- ninfod/ninfod_core.c
- ping6_common.c
- rdisc.c
- tracepath.c
Follow up to pull requests #213 & #214. In this revision feedback mostly from #214 is added to commits, and clockdiff(8) commit message has couple words why ppoll(2) replaced select(2) calls.
If I don't hear anything by Sunday 2019-09-15 I will just merge these change. I am optimistic most of the review already happen in couple earlier pulls.
> More gettimeofday removals

- ping/ping.c
socket bind fails if the IPv6 source address family is not
initialised to AF_INET6.
Signed-off-by: Patrick Ruddy <pruddy@vyatta.att-mail.com>
> ping6: missing init of v6 socket address family

- ping/ping.c
Earlier 'ping -W 1s ...' worked without complaints, but the user interface
regression broke that.  Notice that none-numeric value was simply ignored,
so '-W 1s' and and '-W 1h' meant the same although they looked different.
That was misleading, but because values still managed to work for next
couple releases accepting number with garbage at end is re-introduced.
Regression-since; 918e824dc13a39e4d68fcd82fd2d248c9fba6bbd
Addresses: https://github.com/iputils/iputils/issues/236
Signed-off-by: Sami Kerola <kerolasa@iki.fi>
> ping: allow -i and -W option arguments contain garbage input

- meson.build
libidn2 can optionnaly depends on libunistring so use dependency
function instead of cc.find_library ro retrieve this dependency and
avoid the following build failure when building statically:
```
FAILED: ping
/home/buildroot/autobuild/run/instance-1/output-1/host/bin/arm-linux-gcc  -o ping 'ping@exe/ping.c.o' 'ping@exe/ping_common.c.o' 'ping@exe/ping6_common.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -static -Wl,--start-group libcommon.a -lm -lcap -lidn2 /home/buildroot/autobuild/run/instance-1/output-1/host/usr/bin/../arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libssl.a /home/buildroot/autobuild/run/instance-1/output-1/host/usr/bin/../arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libz.a /home/buildroot/autobuild/run/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc …
```
> meson.build: fix static build with libidn2

- ping/ping_common.c
The code switches from 3 to 4 significant digits because
of mismanaged rounding effects.
Example:
µseconds  ORIGINAL CODE        PATCHED CODE
9993  time=9.99 ms          9993  time=9.99 ms
9994  time=9.99 ms          9994  time=9.99 ms
9995  time=10.00 ms     |   9995  time=10.0 ms
9996  time=10.00 ms     |   9996  time=10.0 ms
...
9998  time=10.00 ms     |   9998  time=10.0 ms
9999  time=10.00 ms     |   9999  time=10.0 ms
10000  time=10.0 ms         10000  time=10.0 ms
10001  time=10.0 ms         10001  time=10.0 ms
> ping: Fix inconsistent usage of decimals when reporting times.

- ping/ping.c
When receiving an ICMP redirect message, ping prints the nexthop,
but this is shown with the wrong endianness on x86:
$ ping 192.168.0.1
PING 192.168.0.1 (192.168.0.1) 56(84) bytes of data.
64 bytes from 192.168.0.1: icmp_seq=1 ttl=254 time=3.41 ms
From 192.168.85.1 icmp_seq=2 Redirect Host(New nexthop: 44.85.168.192)
64 bytes from 192.168.0.1: icmp_seq=2 ttl=254 time=3.75 ms
This only happens when using IPPROTO_ICMP sockets, with raw sockets the
issue doesn't happen:
$ sudo sysctl -w net.ipv4.ping_group_range='1 0'
net.ipv4.ping_group_range = 1 0
$ sudo ping 192.168.0.1
PING 192.168.0.1 (192.168.0.1) 56(84) bytes of data.
64 bytes from 192.168.0.1: icmp_seq=1 ttl=254 time=3.17 ms
From 192.168.85.1: icmp_seq=2 Redirect Host(New nexthop: 192.168.85.44)
64 bytes from 192.168.0.1: icmp_seq=2 …
> ping: print the gateway with the correct endianness

- ping/ping.c
- ping/ping6_common.c
RFC 1122 clearly states that the IP address in the reply MUST match the
one in the request:
The IP source address in an ICMP Echo Reply MUST be the same
as the specific-destination address (defined in Section
3.2.1.3) of the corresponding ICMP Echo Request message.
This is not enforced in iputils neither in IPv4 nor in IPv6:
$ ping -c4 127.0.0.1
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.5: icmp_seq=1 ttl=64 time=0.072 ms
64 bytes from 127.0.0.5: icmp_seq=2 ttl=64 time=0.101 ms
64 bytes from 127.0.0.5: icmp_seq=3 ttl=64 time=0.079 ms
64 bytes from 127.0.0.5: icmp_seq=4 ttl=64 time=0.081 ms
--- 127.0.0.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3056ms
rtt min/avg/max/mdev = 0.072/0.083/0.101/0.010 ms
$ ping -c4 ::1
PING …
> ping: discard packets with wrong source address

- ping/ping.c
- ping/ping6_common.c
If `recvmsg(..., MSG_ERRQUEUE)` returned error, `ping` can misinterpret `EHOSTUNREACH` from `recvmsg` in the main loop as error that happened from his own packets and print the following message:
ping: recvmsg: No route to host
However, this also could be an error from other ping, that was received by this process because of RAW socket. So it's better to skip this error and process it properly in the next cycle.
> ping: process interrupts in ping*_receive_error_msg

- doc/ping.xml
Fix wording and formatting of IPV6 LINK-LOCAL DESTINATIONS section. 
Also move it below OPTIONS section.
Fixes: ed7c27d ("man/ping: Add "IPV6 LINK-LOCAL DESTINATIONS" section")
Reported-by: Benjamin Poirier <benjamin.poirier@gmail.com>
Reviewed-by: Benjamin Poirier <benjamin.poirier@gmail.com>
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>
> man/ping: Fix wording, formatting

- ping/ping.c
Restore back check for -i <= 0.
Fixes: 918e824 ("ping: add support for sub-second timeouts")
Closes: https://github.com/iputils/iputils/issues/465
> ping: Fix overflow on negative -i

- ping/ping.c
- ping/ping.h
- ping/ping6_common.c
- ping/ping_common.c
Improve too low interval for user on broadcast, multicast and flood
error message.  Instead of printing "raw" interval (i.e. -i value *
1000) it's more user friendly to print requested -i value.
```
$ ./builddir/ping/ping -b 192.168.122.255 -i0.1
WARNING: pinging broadcast address
./builddir/ping/ping: minimal interval for broadcast ping for user must be >= 1000 ms, use -i 1 (or higher)
$ ./builddir/ping/ping -i0.1 ff02::1%tun0
./builddir/ping/ping: minimal interval for multicast ping for user must be >= 1000 ms, use -i 1 (or higher)
```
Too low -i value and -f for user without -i use the same message. Not
sure if this should be further improved:
```
$ ./builddir/ping/ping ::1 -f
PING ::1 (::1) 56 data bytes
./builddir/ping/ping: cannot flood, minimal interval for user must be >= 2 ms, …
```
> ping: Make interval error messages more readable

- ping/node_info.c
- ping/ping.c
- ping/ping.h
- ping/ping6_common.c
- ping/ping_common.c
This reverts commit 5026c2221a15bf13e601eade015c971bf07a27e9.
Unlike TCP and UDP, which use port to uniquely identify the socket to deliver data, ICMP use identifier field (ID) to identify the socket.
Therefore if on the same machine, at the same time, two ping processes use the same ID, echo reply can be delivered to the wrong socket.
This is known problem due 16 bit ID field (65535). We used to use PID to get unique number. The default value of /proc/sys/kernel/pid_max is 32768 (half).
The problem is not new, but it was hidden until 5f6bec5 ("ping: Print reply with wrong source with warning").  5026c22 changed it to use our random implementation to increase security. But that actually increases the collisions on systems with highly using ping: e.g. ping run with Nagios via Debian …
> Revert "ping: use random value for the identifier field"

- tracepath.c
`ctl.ai` 'potentially' can be null when we reach `switch()` statement because of loop above,
so we should check that `ctl.ai` is not NULL.
> tracepath: Fix possible nullptr dereference.

- doc/ping.xml
This is a follow up of d466aab ("Revert "ping: use random value for the identifier field"").
> man/ping: Document collisions and pid_max

- build-aux/setcap-setuid.sh
- doc/ping.xml
- ping/ping.c
- ping/ping.h
- ping/ping6_common.c
- ping/ping_common.c
ping: Refactor socket mark failure handling
Ping warned 2x about setsockopt SO_MARK failure, because since 08f0e17 is called also for probe socket (before it was only on real socket):
$ ping -m 2 ::1
ping: WARNING: failed to set mark: 2: Operation not permitted
PING ::1 (::1) 56 data bytes
ping: WARNING: failed to set mark: 2: Operation not permitted
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.039 ms
Therefore pass rts struct to:
1) Disable SO_MARK call on real socket when it failed on probe socket,
therefore only single warning is printed.
2) Print hint about possible missing cap_net_admin+p capability
```
$ ./builddir/ping/ping -m 2 ::1
./builddir/ping/ping: WARNING: failed to set mark: 2: Operation not permitted
./builddir/ping/ping: => missing cap_net_admin+p capability?
PING ::1 …
```
> Add `cap_net_admin`, refactor socket mark failure handling

- arping.c
https://github.com/iputils/iputils/commit/4db1de672559804bebcb7073d231924339ca8cd8 tried to fix a regression 1 sec delay due poll() for unsolicited ARP, .i.e. -A and -U (introduced in https://github.com/iputils/iputils/commit/67e070d08dcbec990e1178360f82b3e2ca4f6d5f, reported as issue https://github.com/iputils/iputils/issues/536). But skipping the while loop entirely introduced another regression for `-A` and `-U`, which behave like `-c1` (sending *always* only a single packet).
Fixing it by checking in while loop and comparing also count (as it was done in https://github.com/iputils/iputils/commit/67e070d08dcbec990e1178360f82b3e2ca4f6d5f before the rewrite).
Fixes: 4db1de6 ("arping: Fix 1s delay on exit for unsolicited arpings")
Fixes: …
> arping: optimize 1s loop delay for unsolicited ARP + fix regression 4db1de6

- doc/ping.xml
- ping/ping.c
- ping/ping.h
- ping/ping6_common.c
- ping/ping_common.c
There are various fixes, which started as fix integer overflow for high -s value. But there are also other fixes (e.g. `ping: Fix EMSGSIZE on -s > 65527 on ICMP datagram socket` in the second commit).
a647e2c commit increased value max allowed -s value from 127992 to INT_MAX (2147483647). To have space for this range datalen was changed from signed int to size_t, but it forgot to change other int variables which also work with this data (hold, packlen).
This fixes signed integer overflow:
```
$ export CC="clang"
$ export CFLAGS="-O0 -g -fsanitize=address,undefined" 
$ export LDFLAGS="-O0 -g -fsanitize=address,undefined" 
$ ./configure && make
$ ./builddir/ping/ping -s 2147483647 ::1
../ping/ping6_common.c:317:7: runtime error: signed integer overflow: -2147483641 + -1174404560 cannot be …
```
> ping: Fix integer overflow for high -s values

- doc/ping.xml
- ping/ping.c
Allow to disable reverse DNS resolution (PTR lookup) with IPUTILS_PING_PTR_LOOKUP environment variable set to 0:
$ IPUTILS_PING_PTR_LOOKUP=0 ./builddir/ping/ping -c1 google.com
PING google.com (142.251.37.110) 56(84) bytes of data.
64 bytes from 142.251.37.110: icmp_seq=1 ttl=116 time=11.1 ms
It's off by default:
$ ./builddir/ping/ping -c1 google.com
PING google.com (142.251.37.110) 56(84) bytes of data.
64 bytes from prg03s13-in-f14.1e100.net (142.251.37.110): icmp_seq=1 ttl=116 time=18.6 ms
`-H/-n` override the variable:
$ IPUTILS_PING_PTR_LOOKUP=0 ./builddir/ping/ping -c1 -H google.com
PING google.com (142.251.37.110) 56(84) bytes of data.
64 bytes from prg03s13-in-f14.1e100.net (142.251.37.110): icmp_seq=1 ttl=116 time=17.1 ms
$ IPUTILS_PING_PTR_LOOKUP= ./builddir/ping/ping -c1 -n …
> ping: Allow to disable with environment variable

- ping/ping_common.c
- po/cs.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/id.po
- po/iputils.pot
- po/ja.po
- po/ka.po
- po/kab.po
- po/ko.po
- po/pt_BR.po
- po/ro.po
- po/tr.po
- po/uk.po
- po/zh_CN.po
Tiny i18n related improvement. Phrase `"time=... ms"` should be translated only once. To achieve it avoid float printf formatting in `_()` gettext.
> Reduce duplicity in translation strings

- ping/ping_common.c
Maximum of preload value (-l) is 65536, but due multiplication with packat size (-s) there can be integer overflow:
$ export CFLAGS="-O1 -g -fsanitize=address,undefined -fno-omit-frame-pointer"
$ meson setup ..
$ ninja && sudo ./ping/ping -c1 -l 65536 -s 30000 ::1
../ping/ping_common.c:451:24: runtime error: signed integer overflow: 65536 * 46528 cannot be represented in type 'int'
PING ::1 (::1) 30000 data bytes
30008 bytes from ::1: icmp_seq=1 ttl=64 time=0.052 ms
Because setsockopt() requires int, instead of making hold and rcvbuf variables bigger (long int) limit them to INT_MAX. This will often lead to warning about rcvbuf is not enough to hold preload, because on current kernel 6.14 and ICMP datagram socket is the max. socket buffer size 425984, but probably better not to depend on …
> ping: Fix integer overflow in large -s and -l values

- ping/ping.c
- ping/ping.h
- ping/ping_common.c
918e824 changed probably as a side effect max -W (time to wait for a response in sec) value from INT_MAX / 1000000 (i.e. 2147 s => ~ 35 min) to INT_MAX / 1000 (i.e. 2147483 s => ~ 586 h).  This allows int overflow with -W > 2148 s (value which was not previously allowed):
$ export CFLAGS="-O1 -g -fsanitize=address,undefined -fno-omit-frame-pointer"
$ meson setup ..
$ ninja && ./ping/ping -c1 -W 2148 8.8.8.8
../ping/ping_common.c:269:37: runtime error: signed integer overflow: 2148000 * 1000 cannot be represented in type 'int'
It could be fixed by simple casting global_rts->lingertime in:
waittime = (unsigned long)global_rts->lingertime * 1000;
But because max -W value is unreasonably large anyway fix the problem by:
1) storing lingertime as uint32_t (fixed 32bit unsigned int, requires …
> ping: Fix integer overflow in large -W value
